### PR TITLE
Upgrade to Google Prediction API v1.6

### PR DESCRIPTION
**Pull request by eliasbaixas**
please apply this change

### CODE REVIEW

**Comment by marloncarvalho** [comment]
Great work, @eliasbaixas! I'm looking forward to have these changes available. Any guess when this pull request will be accepted, @marclove?

**Comment by marclove** [comment]
Thanks for the mention @marloncarvalho. For some reason GitHub didn't notify me of the PR, so I wasn't even aware it was waiting for acceptance.

**Comment by marloncarvalho** [comment]
Great! :+1:  Thank you!

**Comment by eliasbaixas** [comment]
thanks @marclove and @marloncarvalho  :)

**Pull request merged**
